### PR TITLE
Added ability to set a threshold for temperature changes

### PR DESCRIPTION
**Pull request by OliverWieland**
I added a new parameter "Temperature threshold". A temperature message will be published only when the temperature changed at least by this threshold since the last message.

### CODE REVIEW

**Comment by foosel** [comment]
Currently 🤧, will take a look as soon as I can. Btw, by creating this PR against your copy of `master` and merging your event selection feature on that already, this PR now contains those commits as well. To avoid this, it's usually best to create specific branches and use those as base for your PR.

**Comment by OliverWieland** [comment]
Ooops..
I didn't think about merging the event selection feature on my master branch...
I will create a new branch for this feature when I'm at home.

Get well soon... :-)

**Comment by foosel** [comment]
New PR would be great :) And thanks, working on getting back on my feet.

**Comment by OliverWieland** [comment]
Ok, I'll close this one...

**Pull request closed without merging**
