### PR TITLE
mask empty temperatures, eg bed or chamber

### LINKED ISSUE #61: Undesired messages for non-existing chamber temperature
#### What were you doing?

* Updated to latest OctoPrint release
* Installed and configured the MQTT plugin
* Watched the topics with `mosquito_sub -v -t octoprint/#`

The printer profile correctly reflects the missing heated chamber:
grafik

#### What did you expect to happen?
temperate messages for `bed` and `tool0` only

#### What happened instead?
regular temperate messages for `chamber` with updating `_timestamp` readings and temperature values `null`

#### Version of OctoPrint

OctoPrint 1.3.11 auf OctoPi 0.16.0

#### Version of the MQTT plugin

0.8.1

#### Screenshot showing the problem

```
octoprint/temperature/chamber {"_timestamp": 1557933342, "actual": null, "target": null}
octoprint/temperature/bed {"_timestamp": 1557933342, "actual": 24.22, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1557933345, "actual": null, "target": null}
octoprint/temperature/bed {"_timestamp": 1557933345, "actual": 23.98, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1557933348, "actual": null, "target": null}
octoprint/temperature/tool0 {"_timestamp": 1557933348, "actual": 23.24, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1557933351, "actual": null, "target": null}
octoprint/temperature/tool0 {"_timestamp": 1557933351, "actual": 23.52, "target": 0.0}
octoprint/temperature/bed {"_timestamp": 1557933351, "actual": 24.14, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1557933354, "actual": null, "target": null}
octoprint/temperature/bed {"_timestamp": 1557933354, "actual": 23.91, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1557933357, "actual": null, "target": null}
octoprint/temperature/bed {"_timestamp": 1557933357, "actual": 24.1, "target": 0.0}
```

### PR DESCRIPTION
**Pull request by tedder**
- Fixes #61 and probably fixes a case where the bed isn't heated too.
- use `six` to check for stringiness. Should help with py2/py3.
- adjusted some whitespace per `flake`.
- prep for release

I'm going to let this bake on my Pis for a day or two.

### CODE REVIEW

**Comment by jneilliii** [comment]
The logic in code looks sound to me.  I'll be able to test over the weekend.  May want to get @gandy92 to test as well since he/she reported the issue.

**Comment by tedder** [comment]
Don't grab it yet, I have a redone version locally, including the template change. My printers are busy so I haven't gotten to finish the smoke testing.

**Comment by tedder** [comment]
Actually I lied- this is ready, it's the retain flag that needs more analysis. So @gandy92 do you know how to install a prerelease?

**Comment by gandy92** [comment]
@tedder: Not yet, can you tell me roughly what needs to be done? Assume I know my way around the shell, pip and git.

**Comment by jneilliii** [comment]
It's not even that difficult. Go into plugin manager and use the url below to install. 

https://github.com/OctoPrint/OctoPrint-MQTT/archive/ted/61/mask_empty_temps.zip

**Comment by gandy92** [comment]
Now that is boring... :-) but thanks, I'll give it a try.

**Comment by gandy92** [comment]
MQTT topics before the fix:
```
octoprint/temperature/chamber {"_timestamp": 1558515653, "actual": null, "target": null}
octoprint/temperature/tool0 {"_timestamp": 1558515653, "actual": 23.05, "target": 0.0}
octoprint/temperature/bed {"_timestamp": 1558515653, "actual": 24.45, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1558515656, "actual": null, "target": null}
octoprint/temperature/tool0 {"_timestamp": 1558515656, "actual": 23.87, "target": 0.0}
octoprint/temperature/bed {"_timestamp": 1558515656, "actual": 23.98, "target": 0.0}
octoprint/temperature/chamber {"_timestamp": 1558515659, "actual": null, "target": null}
octoprint/temperature/tool0 {"_timestamp": 1558515659, "actual": 23.55, "target": 0.0}
octoprint/temperature/bed {"_timestamp": 1558515659, "actual": 24.3, "target": 0.0}
```

Now with the fix, the topics are restricted to temperature readings from entities that are currently switched on, e.g. when setting a bed tempeature of 55° (`M140 S55`) starting vom 24° ambient, I get:
```
octoprint/temperature/bed {"_timestamp": 1558515861, "actual": 24.3, "target": 55.0}
octoprint/temperature/bed {"_timestamp": 1558515867, "actual": 24.65, "target": 55.0}
octoprint/temperature/bed {"_timestamp": 1558515869, "actual": 25.62, "target": 55.0}
octoprint/temperature/bed {"_timestamp": 1558515871, "actual": 26.51, "target": 55.0}
octoprint/temperature/bed {"_timestamp": 1558515873, "actual": 27.33, "target": 55.0}
```
Now, switching the bed temperature off again (`M140 S0`) silences the bed temperature topics completely. 

Setting a low temperature (`M140 S1`) brings the temperature topics back, but IMHO it should also work when the heater entity is off (in contrast to a missing heater entity).

**Comment by tedder** [comment]
Boolean math is hard, part two. I've fixed the math, can you install and try again? You exposed a great test case that I missed.

**Comment by gandy92** [comment]
Works like a charm now, thank you! 

Tested different set temperatures for bed and tool, even added and removed the chamber from my printer config. Every time, the topics reflected exactly the present heater entities.

**Pull request merged**
