### PR TITLE
Paused for user

### PR DESCRIPTION
**Pull request by erichstuder**
Hello

This could be a solution to #135.
I tested it on my mk3s by causing mechanical collisions by hand.
It works fine.

Questions:
- Is this the right way to solve this?
- Could there be race conditions due to the fact that the event-topic is now fired from 2 different places? Although in my tests it wasn't a problem.

Thank you in advance for your review
erichstuder

### CODE REVIEW

**Comment by jneilliii** [comment]
I think this solution would be fine, but I wonder if it might be better to implement a list of gcode received commands to handle rather than just focus on the single `echo:busy: paused for user` command? I've done something similar in my unpublished [firmware error handler plugin](https://github.com/jneilliii/OctoPrint-FirmwareErrorHandler/blob/master/octoprint_FirmwareErrorHandler/__init__.py).

**Comment by erichstuder** [comment]
I also thought of a list, but as I don't know what other commands could be helpful I left it as it is. If more checks are added a refactoring could be helpful.

**Comment by tideline3d** [comment]
I stumbled on this just now and will be testing soon.   I know Gastion from OctoPod put in some specifics to address this too, looks like he monitors a couple other commands as well. 

https://github.com/gdombiak/OctoPrint-OctoPod/blob/fda20ce2ecfd71ba911acc2ca294c116f04a89dd/octoprint_octopod/paused_for_user.py#L19

**Comment by tideline3d** [comment]
TopTemp does this a really neat way, it lets you define custom Regular Expressions to watch for items in the incoming gcode messages.   Maybe this would a bit more flexible way of solving custom MQTT messaging from the gcode data.  

Here's an example looking for the Bed Power output from the temperature reporting string on a Prusa

image

Here's the string it's watching.   The RPM data is added by issuing M155 S2 C3 (c3 adds fan data).  
Recv: T:20.2 /0.0 B:20.9 /0.0 T0:20.2 /0.0 @:0 B@:0 P:0.0 A:26.6
Recv: E0:0 RPM PRN1:0 RPM E0@:0 PRN1@:0

**Pull request merged**
