### PR TITLE
fix NoneType errors on temperatures

### LINKED ISSUE #42: Expection in plugin when adding temprature point
#### What were you doing?
I updated octoprint to the latest version. 
I have both MQTT and IFTT plugins installed 
IFTT started spamming ClientOpened messages every few seconds = disabling MQTT plugin made it stop 
i saw errors in the log

#### What did you expect to happen?

no errors.  and no ClientOpen messages every few seconds

#### What happened instead?
errors:

the client causes something to crash with other plugins (IFTTT plugin keeps sending the OpenClient message ) and I see these errors in the log 

#### Version of OctoPrint
OctoPrint 1.3.8 running on OctoPi 0.14.0

#### Version of the MQTT plugin
MQTT (0.7.1)

#### Link to octoprint.log

Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:53,387 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb4
03b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:55,370 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb4
03b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:56,298 - octoprint.plugins.IFTTTmaker - INFO - URL: https://maker.ifttt.com/trigger/op-ClientOpened/with/key/dUWVcmGy4B_FUwT8D0Zgit
2018-05-13 15:30:56,331 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: Congratulations! You've fired the op-ClientOpened event Payload: {'value3': '192.168.1.108', 'value2': '', 'value1': ''}
2018-05-13 15:30:56,443 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.108
2018-05-13 15:30:56,521 - octoprint.plugins.IFTTTmaker - INFO - Event skipped: ClientClosed
2018-05-13 15:30:57,404 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb403b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature

Do you need the full log or is this engouh?

### PR DESCRIPTION
**Pull request by tedder**
Fixes #42 and #56, which is almost exactly the same thing. I'd forgotten this wasn't merged when @jneilliii took over the repo and released "0.8.0".

Needs some refreshed testing, please note on the PR if you have installed the PR version and it works/fails.
    
You can install this PR by using the following URL in your plugin install "from URL" panel. I think.
    
    https://github.com/OctoPrint/OctoPrint-MQTT/archive/201811_safer_temperature_evaluation_d.zip

### CODE REVIEW

**Comment by jneilliii** [comment]
It's working for me, only issue is that version is not incremented.  Make that 0.8.1 and I think we're good to go @tedder.

**Comment by tedder** [comment]
done :)

**Comment by tedder** [comment]
rebased+merged and then cut a release here in github. That's it, right? I mean, it isn't on pip, and there's nothing we need to do in Gina's world?

**Comment by jneilliii** [comment]
Yep, that's it.  Once you add the release that will trigger the updates on the end user's side.  I'll verify the release update now to confirm.

**Comment by jneilliii** [comment]
Works perfect.

**Pull request merged**
